import matplotlib.pyplot as plt
import arabic_reshaper
from bidi.algorithm import get_display
import pandas as pd
import numpy as np
import os

# --- Persian Font Setup ---
# This setup assumes a Persian font like Vazir is available.
# In a real application, you'd bundle the font file.
plt.rcParams['font.family'] = 'DejaVu Sans' # A font that supports many glyphs

def to_persian(text):
    """Reshapes and reverses text for proper Persian display in Matplotlib."""
    reshaped_text = arabic_reshaper.reshape(text)
    return get_display(reshaped_text)

def plot_actual_vs_predicted(user_id: int, result_id: int, y_true: pd.Series, y_pred: pd.Series):
    """Generates and saves a plot of actual vs. predicted values."""
    plt.figure(figsize=(12, 6))
    plt.plot(y_true.index, y_true, label=to_persian('مقدار واقعی'))
    plt.plot(y_pred.index, y_pred, label=to_persian('مقدار پیش‌بینی شده'), linestyle='--')

    plt.title(to_persian('مقایسه مقادیر واقعی و پیش‌بینی شده'))
    plt.xlabel(to_persian('تاریخ'))
    plt.ylabel(to_persian('مصرف آب (متر مکعب)'))
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    # Save the plot
    plots_dir = f"backend/user_plots/{user_id}/"
    os.makedirs(plots_dir, exist_ok=True)
    filepath = os.path.join(plots_dir, f"actual_vs_predicted_{result_id}.png")
    plt.savefig(filepath)
    plt.close()
    return filepath

def plot_forecast_with_confidence(user_id: int, result_id: int, forecast_series: pd.Series):
    """Generates and saves a forecast plot with a shaded confidence interval."""
    # --- IMPLEMENTATION NOTE ---
    # This function currently uses the predictions on the training set (`y_pred`)
    # as a stand-in for a real forecast. In a complete implementation, this function
    # would take a genuine forecast series (e.g., for the next 24, 48, 168 hours)
    # as input, generated by the fine-tuned model. The confidence interval
    # would also be calculated based on the model's uncertainty, not randomly generated.
    # -------------------------
    plt.figure(figsize=(12, 6))

    # Generate dummy confidence interval
    confidence = 0.95
    ci = forecast_series * 0.1 * np.random.randn(len(forecast_series)) * 1.96

    plt.plot(forecast_series.index, forecast_series, label=to_persian('پیش‌بینی'))
    plt.fill_between(forecast_series.index,
                     (forecast_series - ci),
                     (forecast_series + ci),
                     color='blue',
                     alpha=0.2,
                     label=to_persian(f'بازه اطمینان {int(confidence*100)}%'))

    plt.title(to_persian('پیش‌بینی مصرف آب به همراه بازه اطمینان'))
    plt.xlabel(to_persian('تاریخ'))
    plt.ylabel(to_persian('مصرف آب (متر مکعب)'))
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    # Save the plot
    plots_dir = f"backend/user_plots/{user_id}/"
    os.makedirs(plots_dir, exist_ok=True)
    filepath = os.path.join(plots_dir, f"forecast_confidence_{result_id}.png")
    plt.savefig(filepath)
    plt.close()

    # For demonstration, let's also return some dummy interval data
    forecast_intervals = forecast_series.to_json()
    confidence_bounds = pd.Series(ci, index=forecast_series.index).to_json()

    return filepath, forecast_intervals, confidence_bounds
